command_timeout = 1500
format = """
$os\
 $directory\
 $git_branch\
 $git_status\
 $direnv\
 $package\
 $bun\
 $nodejs\
 $python\
 $rust\
 $golang\
 $fill\
 $time\
 $cmd_duration\
\
\n$status $character"""

[os]
disabled = false
style = "fg:#769ff0"
format = "[ $symbol]($style)"

[os.symbols]
Fedora = ""
Windows = ""

[directory]
style = "fg:#769ff0"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#769ff0"
format = "[ $symbol $branch]($style)"

[git_status]
style = "fg:#769ff0"
format = "[($all_status$ahead_behind)]($style)"

[direnv]
disabled = false
style = "fg:#769ff0"
format = "[$symbol$loaded/$unloaded]($style)"

[package]
symbol = "📦"
style = "fg:#769ff0"
format = "[ $symbol($version)]($style)"

[bun]
symbol = ""
style = "fg:#769ff0"
format = "[ $symbol($version)]($style)"

[nodejs]
symbol = ""
style = "fg:#769ff0"
format = "[ $symbol($version)]($style)"

[python]
symbol = ""
style = "fg:#769ff0"
format = '[ $symbol($version)(\($venv\))]($style)'
generic_venv_names = [".venv", "venv"]

[rust]
symbol = ""
style = "fg:#769ff0"
format = "[ $symbol($version)]($style)"

[golang]
symbol = ""
style = "fg:#769ff0"
format = "[ $symbol($version)]($style)"

[time]
disabled = false
time_format = "%I:%M %p"
style = "fg:#a0a9cb"
format = "[ $time]($style)"

[cmd_duration]
min_time = 1000
style = "fg:#a0a9cb"
format = "[tardó 祥 $duration]($style)"

[status]
disabled = false
format = "[$symbol $status]($style)"
success_symbol = ""
success_style = ""
failure_style = "fg:red"

[character]
success_symbol = "[➜](fg:#769ff0)"
error_symbol = "[➜](fg:red)"
